error: Change from TritonError to client.ClientError
Paired with @jen20 to diagnose that the wrong error casting was being
done - therefore, compute.IsSpecificError was failing